Added bruck implementation for pmix
artpol84/poc pull request #22
Opened 2020-12-12 13:37 UTC by kkramarenko

Raw bruck implementation

2020-12-12 17:06 UTC, artpol84 commented on MPI/BRUCK/bruck_test.c
> +    return lsb;
```suggestion
    unsigned int number_wo_lsb = number & (number - 1);
    return number - number_wo_lsb;
```

2020-12-12 17:14 UTC, artpol84 commented on MPI/BRUCK/bruck_test.c
> +    tmp = pow(2.0, (int)tmp);
?
```suggestion
    tmp = 1 << (int)tmp;
```

2020-12-12 17:28 UTC, artpol84 commented on MPI/BRUCK/bruck_test.c
> +	    debug_print("rank - %d prepend offset = %d\n", rank, buffer_send[send_size - 1]);
```suggestion
	    debug_print("rank - %d append offset = %d\n", rank, buffer_send[send_size - 1]);
```

2020-12-12 17:29 UTC, artpol84 commented on MPI/BRUCK/bruck_test.c
> +	//MPI_Probe(recv_rank, 0, MPI_COMM_WORLD, &status[0]);
```suggestion
```

2020-12-12 17:30 UTC, artpol84 commented on MPI/BRUCK/bruck_test.c
> +	//debug_print("rank - %d error0 = %d error1 = %d\n", rank, status[0].MPI_ERROR, status[1].MPI_ERROR);
```suggestion
```

2020-12-12 17:32 UTC, artpol84 commented on MPI/BRUCK/bruck_test.c
> +	free(buffer_recv);
выравнивание табом

2020-12-12 17:32 UTC, artpol84 commented on MPI/BRUCK/bruck_test.c
> +    }
Выравнивание пробелом

2020-12-12 17:32 UTC, artpol84 commented on MPI/BRUCK/bruck_test.c
> +	debug_print("rank - %d offset<>0 and = %d\n", rank, offset);
не выровнен

2020-12-12 17:38 UTC, artpol84 commented on MPI/BRUCK/bruck_test.c
> +
Предлагаю добавить проверку результата.
Примерно так (черновой набросок):
```C
    MPI_Allreduce(block_size, MPI_SUM, buffer_mpi_size);
    assert( buffer_size == buffer_mpi_size);
    buffer_mpi = calloc(buffer_mpi_size);
    MPI_Allgatherv(...., buffer_mpi, ...);
    qsort(buffer, ... );
    qsort(buffer_mpi);
    assert( !memcmp(buffer, buffer_mpi));
```

2020-12-12 17:40 UTC, artpol84 requested changes
+ к замечаниям  еще поправить выравнивание.
Предлагаю использовать пробелы (4 пробела).

2020-12-12 23:50 UTC, kkramarenko commented on MPI/BRUCK/bruck_test.c
> +
Как раз и планировал добавить валидацию.

2020-12-12 23:52 UTC, kkramarenko commented on MPI/BRUCK/bruck_test.c
> +    return lsb;
Красота!)

2020-12-13 16:35 UTC, artpol84 commented
Теперь переключаемся на Slurm :)

2020-12-13 16:35 UTC, merged

2020-12-14 02:31 UTC, kkramarenko commented
Хорошо! До среды тогда буду разбираться с реализацией в slurm.